version: "3"

services: 
    scrap_tools:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./scrap_tools:/scrap_tools
        command: >
            sh -c "python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
            - SECRET_KEY=jezdvp7mg)j!5%r3$u6=*wzri3%p&1x%%%0&j^jz-zyrbwilrl
            - ELPAIS_URL=https://elpais.com
            - FACEBOOK_URL=https://facebook.com
            - FB_EMAIL=< your email here >
            - FB_PASS=< your password here >
        depends_on:
            - db
            - hub
            - chrome
    db:
        image: postgres:10-alpine
        environment:
        - POSTGRES_DB=app
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=supersecretpassword

    chrome:
        image: selenium/node-chrome:4.0.0-alpha-7-prerelease-20200826
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - hub
        environment:
            - SE_EVENT_BUS_HOST=hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    
    hub:
        image: selenium/hub:4.0.0-alpha-7-prerelease-20200826
        container_name: hub
        ports:
        - "4442:4442"
        - "4443:4443"
        - "4444:4444"
            